/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;


public class AppTest {
    @Test
    public void appHasAGreeting() {

    }
}
